app1/urls.py
from django.urls import path
from app1.views import *
app_name='one'
urlpatterns=[
    path('animals/',animals,name='animals'),
    path('birds/',birds,name='birds'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('fishes/',fishes,name='fishes'),
    path('reptils/',reptils,name='reptils'),
  
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def animals(request):
    return render(request,'animals.html')

def birds(request):
    return render(request,'birds.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def reptils(request):
    return render(request,'reptils.html')

def fishes(request):
    return render(request,'fishes.html')

templates/animals.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <center><a href="{% url 'one:birds' %}">GO TO BIRDS PAGE</a></center>   
    <center><a href="{% url 'fishes' %}">GO TO FIDHES PAGE</a></center>    
    <center><a href="{% url 'reptils' %}">GO TO REPTILS PAGE</a></center>    
     <center><h1>this is html page of animals</h1></center>   
    
    
</body>
</html>

templates/birds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
        <center><a href="{% url 'one:animals' %}">GO TO ANIMALS PAGE</a></center>
        <center><a href="{% url 'fishes' %}">GO TO FISHES PAGE</a></center>
        <center><a href="{% url 'reptils' %}">GO TO REPTILS PAGE</a></center>
        <center><h1>this is html page of birds</h1></center>
   
</body>
</html>

templates/fishes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <center><a href="{% url 'one:animals' %}">GO TO ANIMALS PAGE</a></center>    
    <center><a href="{% url 'one:birds' %}">GO TO BIRDS PAGE</a></center>    
    <center><a href="{% url 'reptils' %}">GO TO REPTILS PAGE</a></center>  
    <center><h1>this is html page of fishes</h1></center>    
   
</body>
</html>

templates/reptils.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
       <center><a href="{% url 'one:animals' %}">GO TO ANIMALS PAGE</a></center> 
        <center><a href="{% url 'one:birds' %}">GO TO BIRDS PAGE</a></center>
        <center><a href="{% url 'fishes' %}">GO TO FISHES PAGE</a></center>
        <center><h1>this is the html page of reptils</h1></center>

</body>
</html>